version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000